# What this workflow does:
# 1. Install the Notebook2REST tool, and feed the notebooks to it
# 2. Build a docker image of the resulting API, with a new specific versionnumber/tag-name
# 3. Push the docker image to Amazon ECR
# 4. Log in to AWS, and redeploy the helm chart with the new image tag

name: Notebook2REST

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # NOTE: THIS JOB IS A SAMPLE OF HOW WE CAN DO IT LATER
  notebook2rest-setup:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout notebook repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clone notebook2rest tool
        run: |
          git clone https://github.com/Apipilikas/notebook2rest.git
          cd notebook2rest
          pip install -e .
          
      #TODO: steps here to use the notebook2rest on the notebooks
      #TODO: Steps here to create & use automated tests on the generated API

      # - name: Run notebook2rest
      #   run: |
      #     notebook2rest notebooks/example.ipynb --out app/

      #TODO: step here to build the result of notebook2rest as a docker image
      #TODO: step here to push the docker image to Amazon ECR

      # ENABLE BUT WITH THE RIGHT 'role-to-assume':
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::259361438396:role/ContainerManager
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: notebook2rest/api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  # redeploy_kubernetes:
  #   runs-on: ubuntu-latest
  #   steps:
      # 1. Log in on AWS
      # 2. Redeploy with new image, e.g.: 
      # - name: Deploy to Kubernetes
      #   run: |
      #     helm upgrade --install notebook-service ./helm/notebook \
      #       --set image.repository=$ECR_REPO \
      #       --set image.tag=$IMAGE_TAG
